name: recipe_app
description: A simple recipe app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
